### ISSUE TITLE
Add Test Suite for Xamarin library support

### ISSUE THREAD

**Issue by nd4p90x** [segmentio/Analytics.NET#157]

**Comment by juliette-ruchel** [comment]
Made a test app in Xamarin for both IOS and Android, the Analytics package worked as expected. Since one of it target frameworks is .NET Standard Xamarin Libraries can include it and make use of it. The main project of a Xamarin project which is a common class library can make use of the nuget and this will run in the other projects as well, independently of the platform they target.
Here are some videos examples for both IOS and Android:
IOS: https://drive.google.com/file/d/1yFZQqBjXhh37iIyjxiXC-iv0YY4fDhif/view?usp=sharing
Android:  https://drive.google.com/file/d/14jgLtIgLJ9MJxX_t3x6VjtSLx5B_xh3B/view?usp=sharing

**Comment by nd4p90x** [comment]
Thank you for verifying this as an option for the consumer
