### ISSUE TITLE
Events not sent to Segment servers: Failed to send analytic event

### ISSUE THREAD

**Issue by mabead** [segmentio/Analytics.NET#167]
In order to get the fix for #163, I used version 3.7.1 of Analytics.Net. Unfortunately, I still get some errors that tell me that messages are lost.

![image](https://user-images.githubusercontent.com/4930754/115295258-8c9fa000-a127-11eb-92ff-6bc41b46b637.png)

I attached about 2000 logs coming from the Analytics.net library. I hope this can help you to isolate the problem.

[loggly_grid_2021-04-19 19_50_44.400724.zip](https://github.com/segmentio/Analytics.NET/files/6338699/loggly_grid_2021-04-19.19_50_44.400724.zip)

**Comment by juliette-ruchel** [comment]
@mabead,

Thanks for the feedback with the log! Looking into it I saw that you got HttpRequestException in two batches (which contain actions) that have a problem when going to be sent to Segment Server:

1. a38c7228-05e5-4ec2-8bb8-ce0aceaeafa1
2. acb93c7d-9c43-46d6-96c4-b02ec3b7d768

First one retries and is sent successful. The problem is the second one (acb93c7d-9c43-46d6-96c4-b02ec3b7d768) which ends failing showing Segment.io request failed in the log you attached.

Could you try setting Timeout and MaxRetryTime for the Config in the Segment Client? By default those values are 5 seconds and 10 seconds respectively. This could improve temporally the request behavior when retrying. However I am making an improvement in how it is taken into account the times it should retry in case an exception when sending the request occurs.

**Comment by mabead** [comment]
Hi @juliette-ruchel . Which value do you suggest that I use for Timeout and MaxRetryTime?

**Comment by juliette-ruchel** [comment]
Hi @mabead, 
I suggest you to try using a Timeout of 10s and a MaxRetryTime of 20s. Probably this will help you sort out your problems for these actions you are trying to send. 

Nevertheless, once these changes we are working on, are up in nuget, I suggest you just configure the MaxRetryTime to 20s.

**Comment by mabead** [comment]
@juliette-ruchel out of curiosity, have you considered using [polly.net](https://github.com/App-vNext/Polly#retry) to implement that whole retry logic? It did simplify my life many many times.

**Comment by juliette-ruchel** [comment]
@mabead I will check on Polly as I have never used it. If you recommend it for sure I will try it and see if it simplifies the whole retry logic in the library. Did you manage to send all Actions to segment Server?

**Comment by mabead** [comment]
@juliette-ruchel Unfortunately, I was not able yet to try the new settings that you sent over.

**Comment by mabead** [comment]
@pooyaj When do you plan to issue a new version of analytics.net that will contain the fix?

**Comment by pooyaj** [comment]
@mabead will push a version by the end of the week at latest.

**Comment by pooyaj** [comment]
@mabead sorry for the delay. Just published `3.8.0`!
