### ISSUE TITLE
Mismatched Dependency

### ISSUE THREAD

**Issue by hankim813** [segmentio/Analytics.NET#28]
Ticket Ref:

https://segment.zendesk.com/agent/tickets/33879

```
You have mismatch in your nuget package dependencies declaration and what the real dependency your dll uses 
Here you from source 
<Reference Include="Newtonsoft.Json"> 
<HintPath>..\packages\Newtonsoft.Json.7.0.1\lib\net35\Newtonsoft.Json.dll</HintPath> 
</Reference 
Here is you package dependency 
<dependencies> 
<group targetFramework=".NETFramework3.5"> 
<dependency id="Newtonsoft.Json" version="4.5.11" /> 
</group> 
</dependencies>
```

**Comment by jbfp** [comment]
Any news on this?

**Comment by jzebedee** [comment]
I've had this same issue. I believe it's because a fully qualified assembly name isn't included in the Segment reference, so it will introduce issues if you add Segment to a project that also uses JSON.NET with a different version.

I've created PR #34 to qualify the version. Are you able to test the change in that PR and see if this resolves your issue?

**Comment by kkolstad** [comment]
Having the same issue, please fix

**Comment by f2prateek** [comment]
@kkolstad @jzebedee has sent a PR https://github.com/segmentio/Analytics.NET/pull/34, can you verify that it resolves your issue?

**Comment by kkolstad** [comment]
@f2prateek just checked, it does indeed

**Comment by kkolstad** [comment]
@f2prateek will there be a new NuGet release to include this fix?

**Comment by f2prateek** [comment]
Realeased in 2.0.3

**Comment by f2prateek** [comment]
https://www.nuget.org/packages/Analytics/2.0.3
