### ISSUE TITLE
Can't use non-Segment types for parameters

### ISSUE THREAD

**Issue by jzebedee** [segmentio/Analytics.NET#36]
Currently, consumers of this library have to either use or extend the `Dict`/`Properties`/`Traits` classes in order to call Segment client methods. This adds unnecessary complexity and an explicit dependency on Segment, not to mention [violating the **I** in SOL**I**D](https://en.wikipedia.org/wiki/Interface_segregation_principle). :stuck_out_tongue: 

I'd like to see this changed to only require the dictionary interface (`IDictionary<string, object>`) for Segment methods instead of the concrete classes. This way, we can pass in custom dictionary objects or just a regular `Dictionary` without having to derive from a class provided by Segment.

See also:
"Why not inherit from List<T>?"
http://stackoverflow.com/a/21694054/102351

"Is it correct to use inheritance instead of name aliasing in c#?"
http://stackoverflow.com/q/147049/102351

"C#: How to create 'aliases' for classes"
http://stackoverflow.com/q/7082238/102351

**Comment by f2prateek** [comment]
I believie was originaly written to add support for type safe setters.

For instance on traits, we would have had a method `setName(String)` and `setAge(int)` (like https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Traits.java#L224-L227). We never got around to it so that's wy the utility isn't as obvious in this library.

**Comment by f2prateek** [comment]
Closed by #47
